#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 282ea472-70f0-43df-8179-b6d931e61305.
# Generated by Session Keeper on 2026-06-30T17:13:17.520Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Check build toolchain availability
# Check whether the build toolchain (wasm-pack, pnpm, cargo) is available before attempting a verification build.
cd /d/cs/Devlop/A/Axiomic/web && command -v wasm-pack && command -v pnpm && command -v cargo && ls src/wasm 2>/dev/null || echo "no wasm dir"

# Verify build emits deploy artifacts
# Run the production PWA build and confirm the _headers and _redirects deploy files are emitted into dist/.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -25 && echo "----- dist root -----" && ls dist && echo "----- header/redirect files -----" && cat dist/_headers dist/_redirects
