#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 2f9674e0-c44e-407e-afba-e223c3f370e5.
# Generated by Session Keeper on 2026-06-21T17:46:31.150Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Run frontend tests
# Run the frontend Vitest suite to verify new tests and existing ones pass.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -50

# Run frontend tests
# Re-run the frontend Vitest suite and capture output.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -60

# Typecheck the web app
# Run the TypeScript typecheck to catch any type errors in the new code.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -30

# Build the web app
# Run the full typecheck + Vite production build to confirm the app compiles.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -25

# Typecheck the proxy
# Typecheck the Cloudflare Worker proxy after the interval/range changes.
cd /d/cs/Devlop/A/Axiomic/proxy && npx tsc --noEmit 2>&1 | tail -20

# Confirm proxy typecheck
# Confirm the proxy typecheck exit code.
cd /d/cs/Devlop/A/Axiomic/proxy && npx tsc --noEmit; echo "exit=$?"

# Final verification
# Run typecheck and the full Vitest suite to confirm everything is green.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && pnpm test 2>&1 | tail -12
