#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 42062dc0-3623-4907-9e81-fd0adf5adbb9.
# Generated by Session Keeper on 2026-06-28T17:06:24.305Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Run new context menu tests
# Run the new ChartContextMenu test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run ChartContextMenu 2>&1 | tail -40

# Get full frontend test count
# Run full frontend suite to get accurate test totals.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -15

# Verify LiveChart context menu tests pass
# Run the new LiveChart context-menu tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run LiveChart 2>&1 | tail -25

# Confirm full suite green
# Run the full frontend test suite to confirm all tests pass.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -12

# Verify measure tool tests pass
# Run the new measure overlay tests and the updated LiveChart tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run ChartMeasureOverlay LiveChart 2>&1 | tail -30

# Delete stale test file
# Remove the old measure overlay test so it can be rewritten.
cd /d/cs/Devlop/A/Axiomic && rm web/src/components/__tests__/ChartMeasureOverlay.test.tsx

# Final green confirmation
# Final confirmation that the entire frontend suite passes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -8

# Check dev server status
# Check whether the Vite dev server is already running.
cd /d/cs/Devlop/A/Axiomic && (curl -s -o /dev/null -w "%{http_code}" http://localhost:5173 2>/dev/null || echo "down")

# Start dev server
# Start the Vite dev server in the background to test the Measure tool live.
cd /d/cs/Devlop/A/Axiomic && pnpm --dir web dev > /tmp/vite.log 2>&1 &
echo "started"

# Confirm dev server up
# Read the Vite startup log and confirm the server is reachable.
sleep 3; cat /tmp/vite.log; echo "---"; curl -s -o /dev/null -w "%{http_code}" http://localhost:5173 2>/dev/null || echo down

# Verify z-index regression test passes
# Run the measure overlay tests including the new z-index regression.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run ChartMeasureOverlay 2>&1 | tail -12

# Start dev server
# Restart the Vite dev server for live testing of the Replay feature.
cd /d/cs/Devlop/A/Axiomic && pnpm --dir web dev > /tmp/vite.log 2>&1 &
echo started

# Verify replay tests pass
# Run the new replay tests plus the updated LiveChart tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run replay useChartReplay ChartReplayBar LiveChart 2>&1 | tail -30

# Confirm dev server up
# Confirm the dev server is up before browser testing.
sleep 2; curl -s -o /dev/null -w "%{http_code}\n" http://localhost:5173 2>/dev/null || echo down; tail -3 /tmp/vite.log

# Verify new tests pass
# Run the new table/toolbar tests.
cd web && pnpm test -- --run candleTable CandleTable ChartToolbar 2>&1 | tail -40

# Verify new tests pass
# Run the new table/toolbar tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run candleTable CandleTable ChartToolbar 2>&1 | tail -45

# Confirm no regressions
# Run the full frontend test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -30

# Check dev server status
# Check if the dev server is already running.
cd /d/cs/Devlop/A/Axiomic/web && (curl -s -o /dev/null -w "%{http_code}" http://localhost:5173/ || echo "down")
