#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 5b269693-753b-489a-9647-850483fb4513.
# Generated by Session Keeper on 2026-06-21T12:45:07.911Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Verify Heikin-Ashi core implementation passes tests
# Run the new Heikin-Ashi test in the Rust core.
cd /d/cs/Devlop/A/Axiomic/core && cargo test heikin 2>&1 | tail -20

# Rebuild WASM with heikin_ashi export
# Rebuild the WASM bundle so the new heikin_ashi export is available to the frontend.
cd /d/cs/Devlop/A/Axiomic/web && pnpm wasm 2>&1 | tail -25

# Typecheck the web frontend
# Run the TypeScript typecheck for the web app.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -30

# Run frontend tests
# Run the web test suite to confirm nothing regressed.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -30

# Verify new chart tests pass
# Run the new chart helper tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test chart 2>&1 | tail -20

# Verify production build and core tests pass
# Run the production Vite build and the full Rust core test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -15 && echo "---CORE---" && cd ../core && cargo test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the chart UI in a browser.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -15

# Verify typecheck and tests pass
# Typecheck and run the full web test suite after the timeframe change.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -10 && echo "---TEST---" && pnpm test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the timeframe fix.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -12

# Start dev server
# Start the Vite dev server in the background and print the local URL.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev > /tmp/vite.log 2>&1 &) && sleep 4 && cat /tmp/vite.log | grep -i local

# Get dev server URL
# Check the Vite dev server log for the local URL.
cat /tmp/vite.log

# Verify typecheck and tests pass
# Run the TypeScript typecheck and the full Vitest suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && echo "===TESTS===" && pnpm test 2>&1 | tail -12
