#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 5b269693-753b-489a-9647-850483fb4513.
# Generated by Session Keeper on 2026-06-21T16:59:18.233Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Verify Heikin-Ashi core implementation passes tests
# Run the new Heikin-Ashi test in the Rust core.
cd /d/cs/Devlop/A/Axiomic/core && cargo test heikin 2>&1 | tail -20

# Rebuild WASM with heikin_ashi export
# Rebuild the WASM bundle so the new heikin_ashi export is available to the frontend.
cd /d/cs/Devlop/A/Axiomic/web && pnpm wasm 2>&1 | tail -25

# Typecheck the web frontend
# Run the TypeScript typecheck for the web app.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -30

# Run frontend tests
# Run the web test suite to confirm nothing regressed.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -30

# Verify new chart tests pass
# Run the new chart helper tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test chart 2>&1 | tail -20

# Verify production build and core tests pass
# Run the production Vite build and the full Rust core test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -15 && echo "---CORE---" && cd ../core && cargo test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the chart UI in a browser.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -15

# Verify typecheck and tests pass
# Typecheck and run the full web test suite after the timeframe change.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -10 && echo "---TEST---" && pnpm test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the timeframe fix.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -12

# Start dev server
# Start the Vite dev server in the background and print the local URL.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev > /tmp/vite.log 2>&1 &) && sleep 4 && cat /tmp/vite.log | grep -i local

# Get dev server URL
# Check the Vite dev server log for the local URL.
cat /tmp/vite.log

# Verify typecheck and tests pass
# Run the TypeScript typecheck and the full Vitest suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && echo "===TESTS===" && pnpm test 2>&1 | tail -12

# Verify typecheck and updated tests pass
# Run the typecheck and the timeframe + chart test suites.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && echo "===TESTS===" && pnpm test timeframe chart 2>&1 | tail -18

# Run full test suite
# Run the full Vitest suite to confirm nothing regressed.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -8

# Confirm typecheck passes
# Final TypeScript typecheck.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -6

# Find yfinance-rs source
# Locate the yfinance-rs crate source to confirm Range enum variants.
find ~/.cargo/registry/src -type d -name 'yfinance-rs-*' 2>/dev/null | head -3

# List Range variants
# Print the Range enum variants from yfinance-rs.
grep -rn "enum Range" -A 30 ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head -45

# Confirm Range variants
# Find the Range enum definition and its long-range variants.
grep -rln "Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head; echo "---"; grep -rn "Y10\|Y5\|Max\|Ytd\|pub enum Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head -30

# List exact Range variants
# Show the Range enum variants from models.rs.
grep -rn "enum Range" -A 40 ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/models.rs

# Find Range variant names
# Locate Range variants in models.rs.
grep -rn "Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/models.rs | grep -i "enum\|D1\|M6\|Y1\|Y5\|Y10\|Max\|=>" | head -40

# List Range variants
# Enumerate all Range variants used in the crate.
grep -rn "Range::" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | grep -oP "Range::\w+" | sort -u

# Confirm full Range enum
# Inspect the Range enum definition in core/mod.rs.
grep -rn "M6\|Mo6\|Y1\|Max\|Ytd\|D5\|M1\|M3" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/mod.rs | head -40

# Confirm Range::Max exists
# Find and print the Range enum declaration.
grep -rln "Max" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | xargs grep -ln "pub enum Range\|enum Range"; echo "==="; grep -rn "pub enum Range" -A 50 $(grep -rln "pub enum Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/) | grep -iP "^\s*[A-Z]\w*,|enum Range|Max|Y1|M6" | head -40

# Verify data crate compiles
# Type-check the data crate to confirm Range::Max and the max range string compile.
cd /d/cs/Devlop/A/Axiomic/data && cargo check 2>&1 | tail -15

# Verify sample data tests pass
# Run the sample data tests including the new default-span assertion.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test sampleData 2>&1 | tail -12

# Verify all tests pass
# Run the full web test suite and the data crate tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -8 && echo "===DATA===" && cd ../data && cargo test 2>&1 | tail -8

# Start dev server
# Start the Vite dev server and print the local URL.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev > /tmp/vite2.log 2>&1 &) && sleep 5 && grep -iE "local|error|port" /tmp/vite2.log | head

# Get dev URL
# Read the dev server log to get the URL.
cat /tmp/vite2.log

# Lint/type-check
# Type-check the frontend.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -20

# Verify lint + tests
# Type-check and run the full test suite after the refactor.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -5 && pnpm test 2>&1 | tail -8

# Inspect ports
# Check which processes are listening on the dev/proxy ports.
netstat -ano | grep -E ":(5173|5174|8787)\b" | head

# Verify Yahoo endpoint
# Confirm Yahoo's chart API returns the expected timestamp/quote arrays without an API key.
curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0" "https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1d" | node -e "let d='';process.stdin.on('data',c=>d+=c).on('end',()=>{const j=JSON.parse(d);const r=j.chart.result[0];const q=r.indicators.quote[0];console.log('ts',r.timestamp.length,'first close',q.close[0],'last close',q.close[q.close.length-1]);})"

# Verify Yahoo endpoint
# Verify Yahoo chart API shape via a temp file to avoid the winpty stdin issue.
curl -s -A "Mozilla/5.0 Chrome/120.0" "https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1d" -o /tmp/yh.json && node -e "const j=require('/tmp/yh.json');const r=j.chart.result[0];const q=r.indicators.quote[0];console.log('bars',r.timestamp.length,'firstClose',q.close[0],'lastClose',q.close[q.close.length-1],'hasNulls',q.close.includes(null));"

# Verify Yahoo endpoint
# Verify Yahoo chart API shape via a workspace-relative temp file.
cd /d/cs/Devlop/A/Axiomic && curl -s -A "Mozilla/5.0 Chrome/120.0" "https://query1.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1d" -o yh.json && node -e "const j=require('./yh.json');const r=j.chart.result[0];const q=r.indicators.quote[0];console.log('bars',r.timestamp.length,'firstClose',q.close[0],'lastClose',q.close[q.close.length-1],'hasNulls',q.close.includes(null));" && rm -f yh.json

# Start proxy
# Start the Cloudflare Worker proxy in dev mode.
cd /d/cs/Devlop/A/Axiomic/proxy && (pnpm dev > /tmp/proxy.log 2>&1 &) && sleep 8 && grep -iE "ready|listening|8787|error" /tmp/proxy.log | head

# Check proxy log
# Read the proxy dev server log.
cat /tmp/proxy.log 2>/dev/null | tail -20

# Confirm proxy ready
# Wait for the proxy to be ready and find its URL.
sleep 4 && cat /tmp/proxy.log 2>/dev/null | grep -iE "ready|localhost|8787" | head

# Test proxy quotes
# Call the proxy's /quotes endpoint and verify it returns candles.
cd /d/cs/Devlop/A/Axiomic && curl -s "http://127.0.0.1:8787/quotes?symbol=AAPL" -o pq.json && node -e "const j=require('./pq.json');console.log('keys',Object.keys(j),'count',j.candles?.length,'first',JSON.stringify(j.candles?.[0]),'last',JSON.stringify(j.candles?.[j.candles.length-1]));" && rm -f pq.json

# Free dev ports
# Kill stale Vite dev servers on 5173/5174 so we can start cleanly on 5173.
cd /d/cs/Devlop/A/Axiomic && for p in 5173 5174; do pid=$(netstat -ano | grep -E ":$p .*LISTENING" | awk '{print $NF}' | head -1); if [ -n "$pid" ]; then taskkill //PID $pid //F >/dev/null 2>&1 && echo "killed $p (pid $pid)"; fi; done; sleep 1; echo done

# Restart web on 5173
# Start the web dev server fresh to validate the strictPort:5173 config.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev > /tmp/vite3.log 2>&1 &) && sleep 6 && grep -iE "local:|strictPort|error|in use|port" /tmp/vite3.log | head

# Get dev URL
# Read the new dev server log for the URL.
cat /tmp/vite3.log | tail -12

# Type-check proxy
# Type-check the rewritten proxy worker.
cd /d/cs/Devlop/A/Axiomic/proxy && npx tsc --noEmit 2>&1 | tail -15 && echo "exit: $?"

# Validate web
# Type-check and run the web test suite after all changes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -4 && pnpm test 2>&1 | tail -6

# Verify Stooq endpoint
# Verify Stooq provides free, no-key daily CSV data as a second web provider.
cd /d/cs/Devlop/A/Axiomic && curl -s "https://stooq.com/q/d/l/?s=aapl.us&i=d" -o stq.csv && head -3 stq.csv && echo "---lines---" && wc -l < stq.csv && tail -2 stq.csv && rm -f stq.csv

# Verify query2 host
# Verify Yahoo's query2 host also serves the chart API without a key.
cd /d/cs/Devlop/A/Axiomic && curl -s -A "Mozilla/5.0 Chrome/120.0" "https://query2.finance.yahoo.com/v8/finance/chart/AAPL?range=1mo&interval=1d" -o yh2.json && node -e "const j=require('./yh2.json');const r=j.chart.result[0];console.log('query2 bars',r.timestamp.length,'lastClose',r.indicators.quote[0].close.slice(-1)[0]);" && rm -f yh2.json

# Validate web
# Type-check and run the web test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -4 && pnpm test 2>&1 | tail -8

# Test proxy provider routing
# Verify the proxy returns data for each provider value (and defaults safely for unknown).
cd /d/cs/Devlop/A/Axiomic && for p in yfinance yahoo bogus; do curl -s "http://127.0.0.1:8787/quotes?symbol=AAPL&provider=$p" -o pq.json 2>/dev/null; node -e "const j=require('./pq.json');console.log('$p ->','candles:',j.candles?.length ?? ('ERR '+JSON.stringify(j)));"; done; rm -f pq.json

# Final validation
# Type-check and test web + type-check proxy after all changes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -3 && pnpm test 2>&1 | tail -6 && cd ../proxy && npx tsc --noEmit && echo "proxy tsc OK"
