#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 5b269693-753b-489a-9647-850483fb4513.
# Generated by Session Keeper on 2026-06-21T13:21:51.470Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Verify Heikin-Ashi core implementation passes tests
# Run the new Heikin-Ashi test in the Rust core.
cd /d/cs/Devlop/A/Axiomic/core && cargo test heikin 2>&1 | tail -20

# Rebuild WASM with heikin_ashi export
# Rebuild the WASM bundle so the new heikin_ashi export is available to the frontend.
cd /d/cs/Devlop/A/Axiomic/web && pnpm wasm 2>&1 | tail -25

# Typecheck the web frontend
# Run the TypeScript typecheck for the web app.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -30

# Run frontend tests
# Run the web test suite to confirm nothing regressed.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -30

# Verify new chart tests pass
# Run the new chart helper tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test chart 2>&1 | tail -20

# Verify production build and core tests pass
# Run the production Vite build and the full Rust core test suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -15 && echo "---CORE---" && cd ../core && cargo test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the chart UI in a browser.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -15

# Verify typecheck and tests pass
# Typecheck and run the full web test suite after the timeframe change.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -10 && echo "---TEST---" && pnpm test 2>&1 | tail -15

# Start dev server
# Start the Vite dev server to validate the timeframe fix.
cd /d/cs/Devlop/A/Axiomic/web && pnpm dev 2>&1 | head -12

# Start dev server
# Start the Vite dev server in the background and print the local URL.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev > /tmp/vite.log 2>&1 &) && sleep 4 && cat /tmp/vite.log | grep -i local

# Get dev server URL
# Check the Vite dev server log for the local URL.
cat /tmp/vite.log

# Verify typecheck and tests pass
# Run the TypeScript typecheck and the full Vitest suite.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && echo "===TESTS===" && pnpm test 2>&1 | tail -12

# Verify typecheck and updated tests pass
# Run the typecheck and the timeframe + chart test suites.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -8 && echo "===TESTS===" && pnpm test timeframe chart 2>&1 | tail -18

# Run full test suite
# Run the full Vitest suite to confirm nothing regressed.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -8

# Confirm typecheck passes
# Final TypeScript typecheck.
cd /d/cs/Devlop/A/Axiomic/web && pnpm lint 2>&1 | tail -6

# Find yfinance-rs source
# Locate the yfinance-rs crate source to confirm Range enum variants.
find ~/.cargo/registry/src -type d -name 'yfinance-rs-*' 2>/dev/null | head -3

# List Range variants
# Print the Range enum variants from yfinance-rs.
grep -rn "enum Range" -A 30 ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head -45

# Confirm Range variants
# Find the Range enum definition and its long-range variants.
grep -rln "Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head; echo "---"; grep -rn "Y10\|Y5\|Max\|Ytd\|pub enum Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | head -30

# List exact Range variants
# Show the Range enum variants from models.rs.
grep -rn "enum Range" -A 40 ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/models.rs

# Find Range variant names
# Locate Range variants in models.rs.
grep -rn "Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/models.rs | grep -i "enum\|D1\|M6\|Y1\|Y5\|Y10\|Max\|=>" | head -40

# List Range variants
# Enumerate all Range variants used in the crate.
grep -rn "Range::" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | grep -oP "Range::\w+" | sort -u

# Confirm full Range enum
# Inspect the Range enum definition in core/mod.rs.
grep -rn "M6\|Mo6\|Y1\|Max\|Ytd\|D5\|M1\|M3" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/core/mod.rs | head -40

# Confirm Range::Max exists
# Find and print the Range enum declaration.
grep -rln "Max" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/ | xargs grep -ln "pub enum Range\|enum Range"; echo "==="; grep -rn "pub enum Range" -A 50 $(grep -rln "pub enum Range" ~/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yfinance-rs-0.9.0/src/) | grep -iP "^\s*[A-Z]\w*,|enum Range|Max|Y1|M6" | head -40

# Verify data crate compiles
# Type-check the data crate to confirm Range::Max and the max range string compile.
cd /d/cs/Devlop/A/Axiomic/data && cargo check 2>&1 | tail -15

# Verify sample data tests pass
# Run the sample data tests including the new default-span assertion.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test sampleData 2>&1 | tail -12

# Verify all tests pass
# Run the full web test suite and the data crate tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test 2>&1 | tail -8 && echo "===DATA===" && cd ../data && cargo test 2>&1 | tail -8
