#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session 632ca598-ba65-44cd-b762-10cff07ead2d.
# Generated by Session Keeper on 2026-06-30T16:44:46.186Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Verify new tests pass
# Run the new Price Targets unit and component tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/priceTargets.test.ts src/components/__tests__/PriceTargetWorkspace.test.tsx 2>&1 | tail -40

# Confirm tests pass
# Re-run the Price Targets tests after fixes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/priceTargets.test.ts src/components/__tests__/PriceTargetWorkspace.test.tsx 2>&1 | tail -25

# Confirm all new tests pass
# Re-run the Price Targets tests after fixing the multi-match query.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/priceTargets.test.ts src/components/__tests__/PriceTargetWorkspace.test.tsx 2>&1 | tail -12

# Verify no regressions
# Run the full frontend test suite and production build (typecheck + Vite).
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -20 && echo "---BUILD---" && pnpm build 2>&1 | tail -15

# Verify new tests pass
# Run the new Position Repair unit and component tests.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/positionRepair.test.ts src/components/__tests__/PositionRepairPanel.test.tsx 2>&1 | tail -40

# Confirm all new tests pass
# Re-run the Position Repair tests after scoping queries to the table.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/positionRepair.test.ts src/components/__tests__/PositionRepairPanel.test.tsx 2>&1 | tail -15

# Verify no regressions
# Run the full frontend suite and production build.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -8 && echo "---BUILD---" && pnpm build 2>&1 | tail -6

# Verify custom-target tests pass
# Run the Position Repair panel tests including the new custom-target cases.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/components/__tests__/PositionRepairPanel.test.tsx 2>&1 | tail -15

# Diagnose the failing assertion
# Inspect the failure detail for the 150.00 query.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/components/__tests__/PositionRepairPanel.test.tsx 2>&1 | grep -A3 -i "error\|unable\|multiple\|150" | head -40

# Confirm green tests and successful build
# Run the full suite and build to confirm no regressions.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -8 && echo "---BUILD---" && pnpm build 2>&1 | tail -4

# Verify generalized tests pass
# Run the updated Position Repair lib + panel tests including averaging-up cases.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run src/lib/__tests__/positionRepair.test.ts src/components/__tests__/PositionRepairPanel.test.tsx 2>&1 | tail -30

# Confirm no regressions
# Run the full frontend suite and production build.
cd /d/cs/Devlop/A/Axiomic/web && pnpm test -- --run 2>&1 | tail -6 && echo "---BUILD---" && pnpm build 2>&1 | tail -4

# Confirm the build is clean
# Final typecheck + build after doc edits.
cd /d/cs/Devlop/A/Axiomic/web && pnpm build 2>&1 | tail -5
