#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session a58d4015-4427-410f-bee5-80d6a7350989.
# Generated by Session Keeper on 2026-06-20T18:03:17.653Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Find Visual Studio Copilot log locations
# Search for any Copilot debug-logs directories under APPDATA and LOCALAPPDATA to find Visual Studio's location.
powershell -NoProfile -Command "Get-ChildItem -Path \$env:LOCALAPPDATA, \$env:APPDATA -Recurse -Directory -Filter 'debug-logs' -ErrorAction SilentlyContinue | Where-Object { \$_.FullName -match 'copilot' } | Select-Object -ExpandProperty FullName"

# Locate VS Copilot folders
# Find any Copilot-related directories under LOCALAPPDATA (Visual Studio location candidate).
powershell -NoProfile -Command "Get-ChildItem -Path \$env:LOCALAPPDATA -Recurse -Directory -ErrorAction SilentlyContinue -Depth 4 | Where-Object { \$_.Name -match 'copilot' } | Select-Object -ExpandProperty FullName | Select-Object -First 40"

# Inspect VS copilot-chat layout
# Inspect the Visual Studio Copilot chat folder layout to compare with VS Code.
powershell -NoProfile -Command "Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat' -Recurse -ErrorAction SilentlyContinue -Depth 3 | Select-Object -ExpandProperty FullName | Select-Object -First 60"

# Find VS session/debug-log files
# List the contents of the Visual Studio copilot-chat sessions folder and search for debug-logs dirs.
powershell -NoProfile -Command "Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat\fb1422a6' -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 80; Write-Output '---DEBUGLOGS---'; Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio' -Recurse -Directory -Filter 'debug-logs' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName"

# Find VS jsonl session logs
# Inspect VS sessions contents, the VS Copilot logs temp folder, and search for any jsonl files.
powershell -NoProfile -Command "Write-Output '=== sessions dir ==='; Get-ChildItem -Force -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat\fb1422a6\sessions' -ErrorAction SilentlyContinue | Format-Table Name,Length,LastWriteTime -Auto; Write-Output '=== VSGitHubCopilotLogs ==='; Get-ChildItem -Force -Recurse -Path 'C:\Users\H300133\AppData\Local\Temp\VSGitHubCopilotLogs' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 40; Write-Output '=== any main.jsonl under VS ==='; Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio' -Recurse -Filter '*.jsonl' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 20"

# Inspect VS chat.log format
# View the head of a Visual Studio Copilot chat log to understand its format.
powershell -NoProfile -Command "$f='C:\Users\H300133\AppData\Local\Temp\VSGitHubCopilotLogs\20260616_030646.430_VSGitHubCopilot.chat.log'; Write-Output ('Size: ' + (Get-Item $f).Length); Get-Content -Path $f -TotalCount 30"

# Inspect VS chat.log format
# View the start of the Visual Studio chat log using bash head to understand format.
head -c 4000 "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log"

# Assess parseability of VS logs
# List the traces folder and find structured markers in the VS chat log.
ls -la "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/traces" 2>/dev/null | head -20; echo "=== grep interesting markers ==="; grep -aoE "(UserMessage|User message|Prompt|tool|Tool call|RunInTerminal|terminal|ToolCall|Reasoning|thinking|assistant|ModelName|model:)" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | sort | uniq -c | sort -rn | head -40

# Examine VS log content lines
# Look at the actual content of marker lines to assess what can be parsed.
echo "=== ToolCall line ==="; grep -an "ToolCall" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== terminal lines ==="; grep -an "terminal" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== Reasoning line ==="; grep -an "Reasoning" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== Prompt lines sample ==="; grep -an "Prompt" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -8

# Find VS structured session data
# Search for any structured session/conversation files Visual Studio may persist.
echo "=== sessions folder (per-version) ==="; find "/c/Users/H300133/AppData/Local/Microsoft/VisualStudio" -path "*copilot-chat*" -type f 2>/dev/null | head -30; echo "=== copilot-vs temp ==="; find "/c/Users/H300133/AppData/Local/Temp/VisualStudio/copilot-vs" -type f 2>/dev/null | head -30; echo "=== any sizable json under VS copilot dirs ==="; find "/c/Users/H300133/AppData/Local/Microsoft/VisualStudio" -iname "*.json" -path "*opilot*" 2>/dev/null | head -20

# Test VS capture path
# Run the script targeting the Visual Studio trace log and inspect the generated summary.
cd /d/cs/Devlop/A/Axiomic && VSCODE_TARGET_SESSION_LOG="/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" SESSION_KEEPER_WORKSPACE="/tmp/sk-vs-test" node ./.github/skills/session-keeper/scripts/keep-session.mjs < /dev/null; echo; echo "=== output tree ==="; find /tmp/sk-vs-test -type f; echo "=== summary ==="; cat /tmp/sk-vs-test/.copilot-sessions/summary/*.md

# Test VS capture cleanly
# Spawn the keep-session script from Node with clean piped stdin to avoid the winpty tty artifact, then inspect output.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,VSCODE_TARGET_SESSION_LOG:'C:/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log',SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-vs-test'}});console.log('STDOUT:',r.stdout);console.error('STDERR:',r.stderr);"; echo "=== tree ==="; find "/c/Users/H300133/AppData/Local/Temp/sk-vs-test" -type f 2>/dev/null; echo "=== summary ==="; cat "/c/Users/H300133/AppData/Local/Temp/sk-vs-test/.copilot-sessions/summary/"*.md 2>/dev/null

# Verify no VS Code regression
# Run the script with auto-discovery to confirm VS Code JSONL logs are still preferred and full artifacts are produced.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-vscode-test'}});console.log('STDOUT:',r.stdout);console.error('STDERR:',r.stderr);"; echo "=== tree ==="; find "/c/Users/H300133/AppData/Local/Temp/sk-vscode-test" -type f 2>/dev/null | head -30

# Clean up test artifacts
# Remove the temporary test output directories.
rm -rf "/c/Users/H300133/AppData/Local/Temp/sk-vs-test" "/c/Users/H300133/AppData/Local/Temp/sk-vscode-test"; echo cleaned

# Locate the session files and sizes
# List the captured logs and find all copies of the session in question to compare sizes.
echo "=== workspace .copilot-sessions/logs ==="; ls -la "/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/" 2>/dev/null; echo; echo "=== find the session id everywhere ==="; find "/c/Users/H300133/AppData/Roaming" -name "9d3f957f-0a5b-4502-92b8-a001d2f610f2*" 2>/dev/null; find "/d/cs/Devlop/A/Axiomic" -name "9d3f957f-0a5b-4502-92b8-a001d2f610f2*" 2>/dev/null

# Check for copy truncation
# Compare byte and line counts between the source debug log and the captured copy to detect truncation.
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "=== SOURCE ==="; ls -la "$SRC"; echo "=== DEST ==="; ls -la "$DST"; echo; echo "src bytes: $(wc -c < "$SRC")"; echo "dst bytes: $(wc -c < "$DST")"; echo "src lines: $(wc -l < "$SRC")"; echo "dst lines: $(wc -l < "$DST")"

# Identify the missed trailing spans
# Inspect the last copied span and the four trailing spans that were missed to confirm they were appended after the snapshot.
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "=== last line of DEST (truncated copy) — type/name/ts ==="; tail -n 1 "$DST" | head -c 300 | python -c "import sys,json; d=json.loads(sys.stdin.read()); print({k:d.get(k) for k in ('ts','type','name','status')})" 2>/dev/null || tail -n 1 "$DST" | cut -c1-200; echo; echo "=== the 4 extra source lines (1210-1213): type/name/ts ==="; sed -n '1210,1213p' "$SRC" | while IFS= read -r l; do echo "$l" | python -c "import sys,json; d=json.loads(sys.stdin.read()); print({k:d.get(k) for k in ('ts','type','name','status')})" 2>/dev/null || echo "${l:0:120}"; done

# Verify copy is a clean prefix
# Confirm the captured copy is byte-identical to the first 1209 lines of the source (a clean prefix, not corrupted).
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "dst sha:"; head -n 1209 "$SRC" | sha256sum; echo "src[1..1209] sha:"; cat "$DST" | sha256sum
