#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session a58d4015-4427-410f-bee5-80d6a7350989.
# Generated by Session Keeper on 2026-06-20T18:57:29.197Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Find Visual Studio Copilot log locations
# Search for any Copilot debug-logs directories under APPDATA and LOCALAPPDATA to find Visual Studio's location.
powershell -NoProfile -Command "Get-ChildItem -Path \$env:LOCALAPPDATA, \$env:APPDATA -Recurse -Directory -Filter 'debug-logs' -ErrorAction SilentlyContinue | Where-Object { \$_.FullName -match 'copilot' } | Select-Object -ExpandProperty FullName"

# Locate VS Copilot folders
# Find any Copilot-related directories under LOCALAPPDATA (Visual Studio location candidate).
powershell -NoProfile -Command "Get-ChildItem -Path \$env:LOCALAPPDATA -Recurse -Directory -ErrorAction SilentlyContinue -Depth 4 | Where-Object { \$_.Name -match 'copilot' } | Select-Object -ExpandProperty FullName | Select-Object -First 40"

# Inspect VS copilot-chat layout
# Inspect the Visual Studio Copilot chat folder layout to compare with VS Code.
powershell -NoProfile -Command "Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat' -Recurse -ErrorAction SilentlyContinue -Depth 3 | Select-Object -ExpandProperty FullName | Select-Object -First 60"

# Find VS session/debug-log files
# List the contents of the Visual Studio copilot-chat sessions folder and search for debug-logs dirs.
powershell -NoProfile -Command "Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat\fb1422a6' -Recurse -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 80; Write-Output '---DEBUGLOGS---'; Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio' -Recurse -Directory -Filter 'debug-logs' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName"

# Find VS jsonl session logs
# Inspect VS sessions contents, the VS Copilot logs temp folder, and search for any jsonl files.
powershell -NoProfile -Command "Write-Output '=== sessions dir ==='; Get-ChildItem -Force -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio\18.0_374f30fc\VSGitHubCopilot\copilot-chat\fb1422a6\sessions' -ErrorAction SilentlyContinue | Format-Table Name,Length,LastWriteTime -Auto; Write-Output '=== VSGitHubCopilotLogs ==='; Get-ChildItem -Force -Recurse -Path 'C:\Users\H300133\AppData\Local\Temp\VSGitHubCopilotLogs' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 40; Write-Output '=== any main.jsonl under VS ==='; Get-ChildItem -Path 'C:\Users\H300133\AppData\Local\Microsoft\VisualStudio' -Recurse -Filter '*.jsonl' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName | Select-Object -First 20"

# Inspect VS chat.log format
# View the head of a Visual Studio Copilot chat log to understand its format.
powershell -NoProfile -Command "$f='C:\Users\H300133\AppData\Local\Temp\VSGitHubCopilotLogs\20260616_030646.430_VSGitHubCopilot.chat.log'; Write-Output ('Size: ' + (Get-Item $f).Length); Get-Content -Path $f -TotalCount 30"

# Inspect VS chat.log format
# View the start of the Visual Studio chat log using bash head to understand format.
head -c 4000 "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log"

# Assess parseability of VS logs
# List the traces folder and find structured markers in the VS chat log.
ls -la "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/traces" 2>/dev/null | head -20; echo "=== grep interesting markers ==="; grep -aoE "(UserMessage|User message|Prompt|tool|Tool call|RunInTerminal|terminal|ToolCall|Reasoning|thinking|assistant|ModelName|model:)" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | sort | uniq -c | sort -rn | head -40

# Examine VS log content lines
# Look at the actual content of marker lines to assess what can be parsed.
echo "=== ToolCall line ==="; grep -an "ToolCall" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== terminal lines ==="; grep -an "terminal" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== Reasoning line ==="; grep -an "Reasoning" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -5; echo "=== Prompt lines sample ==="; grep -an "Prompt" "/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" | head -8

# Find VS structured session data
# Search for any structured session/conversation files Visual Studio may persist.
echo "=== sessions folder (per-version) ==="; find "/c/Users/H300133/AppData/Local/Microsoft/VisualStudio" -path "*copilot-chat*" -type f 2>/dev/null | head -30; echo "=== copilot-vs temp ==="; find "/c/Users/H300133/AppData/Local/Temp/VisualStudio/copilot-vs" -type f 2>/dev/null | head -30; echo "=== any sizable json under VS copilot dirs ==="; find "/c/Users/H300133/AppData/Local/Microsoft/VisualStudio" -iname "*.json" -path "*opilot*" 2>/dev/null | head -20

# Test VS capture path
# Run the script targeting the Visual Studio trace log and inspect the generated summary.
cd /d/cs/Devlop/A/Axiomic && VSCODE_TARGET_SESSION_LOG="/c/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log" SESSION_KEEPER_WORKSPACE="/tmp/sk-vs-test" node ./.github/skills/session-keeper/scripts/keep-session.mjs < /dev/null; echo; echo "=== output tree ==="; find /tmp/sk-vs-test -type f; echo "=== summary ==="; cat /tmp/sk-vs-test/.copilot-sessions/summary/*.md

# Test VS capture cleanly
# Spawn the keep-session script from Node with clean piped stdin to avoid the winpty tty artifact, then inspect output.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,VSCODE_TARGET_SESSION_LOG:'C:/Users/H300133/AppData/Local/Temp/VSGitHubCopilotLogs/20260616_030646.430_VSGitHubCopilot.chat.log',SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-vs-test'}});console.log('STDOUT:',r.stdout);console.error('STDERR:',r.stderr);"; echo "=== tree ==="; find "/c/Users/H300133/AppData/Local/Temp/sk-vs-test" -type f 2>/dev/null; echo "=== summary ==="; cat "/c/Users/H300133/AppData/Local/Temp/sk-vs-test/.copilot-sessions/summary/"*.md 2>/dev/null

# Verify no VS Code regression
# Run the script with auto-discovery to confirm VS Code JSONL logs are still preferred and full artifacts are produced.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-vscode-test'}});console.log('STDOUT:',r.stdout);console.error('STDERR:',r.stderr);"; echo "=== tree ==="; find "/c/Users/H300133/AppData/Local/Temp/sk-vscode-test" -type f 2>/dev/null | head -30

# Clean up test artifacts
# Remove the temporary test output directories.
rm -rf "/c/Users/H300133/AppData/Local/Temp/sk-vs-test" "/c/Users/H300133/AppData/Local/Temp/sk-vscode-test"; echo cleaned

# Locate the session files and sizes
# List the captured logs and find all copies of the session in question to compare sizes.
echo "=== workspace .copilot-sessions/logs ==="; ls -la "/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/" 2>/dev/null; echo; echo "=== find the session id everywhere ==="; find "/c/Users/H300133/AppData/Roaming" -name "9d3f957f-0a5b-4502-92b8-a001d2f610f2*" 2>/dev/null; find "/d/cs/Devlop/A/Axiomic" -name "9d3f957f-0a5b-4502-92b8-a001d2f610f2*" 2>/dev/null

# Check for copy truncation
# Compare byte and line counts between the source debug log and the captured copy to detect truncation.
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "=== SOURCE ==="; ls -la "$SRC"; echo "=== DEST ==="; ls -la "$DST"; echo; echo "src bytes: $(wc -c < "$SRC")"; echo "dst bytes: $(wc -c < "$DST")"; echo "src lines: $(wc -l < "$SRC")"; echo "dst lines: $(wc -l < "$DST")"

# Identify the missed trailing spans
# Inspect the last copied span and the four trailing spans that were missed to confirm they were appended after the snapshot.
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "=== last line of DEST (truncated copy) — type/name/ts ==="; tail -n 1 "$DST" | head -c 300 | python -c "import sys,json; d=json.loads(sys.stdin.read()); print({k:d.get(k) for k in ('ts','type','name','status')})" 2>/dev/null || tail -n 1 "$DST" | cut -c1-200; echo; echo "=== the 4 extra source lines (1210-1213): type/name/ts ==="; sed -n '1210,1213p' "$SRC" | while IFS= read -r l; do echo "$l" | python -c "import sys,json; d=json.loads(sys.stdin.read()); print({k:d.get(k) for k in ('ts','type','name','status')})" 2>/dev/null || echo "${l:0:120}"; done

# Verify copy is a clean prefix
# Confirm the captured copy is byte-identical to the first 1209 lines of the source (a clean prefix, not corrupted).
SRC="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/8a714d6fc35a80f9676c1061ed50311a/GitHub.copilot-chat/debug-logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2/main.jsonl"; DST="/d/cs/Devlop/A/Axiomic/.copilot-sessions/logs/9d3f957f-0a5b-4502-92b8-a001d2f610f2.jsonl"; echo "dst sha:"; head -n 1209 "$SRC" | sha256sum; echo "src[1..1209] sha:"; cat "$DST" | sha256sum

# Inspect skills layout
# List the .github skills/hooks layout and read skill frontmatter to describe accurately.
echo "=== .github tree ==="; find "/d/cs/Devlop/A/Axiomic/.github" -type f | sort; echo; echo "=== session-keeper skill frontmatter ==="; sed -n '1,6p' "/d/cs/Devlop/A/Axiomic/.github/skills/session-keeper/SKILL.md"; echo "=== axiomic-dev skill frontmatter ==="; sed -n '1,8p' "/d/cs/Devlop/A/Axiomic/.github/skills/axiomic-dev/SKILL.md" 2>/dev/null

# List models in logs
# Enumerate all model names seen in llm_request spans to understand model variety.
ROOT="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage"; echo "=== distinct llm_request model names across all logs ==="; find "$ROOT" -name main.jsonl 2>/dev/null | while read -r f; do grep -ho '"type":"llm_request","name":"[^"]*"' "$f" 2>/dev/null; done | sed 's/.*"name":"//; s/"//' | sort | uniq -c | sort -rn | head -40

# Inspect agent_response attrs keys
# Inspect what attrs keys exist on agent_response spans across logs to see reasoning storage variation.
ROOT="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage"; echo "=== which attrs keys appear on agent_response spans (per model context) ==="; find "$ROOT" -name main.jsonl 2>/dev/null | while read -r f; do python - "$f" <<'PY' 2>/dev/null
import sys,json
f=sys.argv[1]
from collections import Counter
keys=Counter(); has_reason=0; total=0
for line in open(f,encoding='utf8',errors='ignore'):
    line=line.strip()
    if not line: continue
    try: d=json.loads(line)
    except: continue
    if d.get('type')=='agent_response' or d.get('name')=='agent_response':
        total+=1
        a=d.get('attrs') or {}
        for k in a: keys[k]+=1
        if a.get('reasoning'): has_reason+=1
print(f, 'agent_response:',total,'with_reasoning:',has_reason, dict(keys))
PY
done | head -30

# Find reasoning fallback location
# Check a zero-reasoning session for model name and whether reasoning is embedded in llm_request payloads.
F="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/02dacec274c340c6583f5041ef522e69/GitHub.copilot-chat/debug-logs/66911b60-e046-40bc-8401-2db901e191ca/main.jsonl"; python - "$F" <<'PY'
import sys,json
f=sys.argv[1]
models=set(); llm_attr_keys=set(); reasoning_in_llm=0; sample=None
for line in open(f,encoding='utf8',errors='ignore'):
    line=line.strip()
    if not line: continue
    try: d=json.loads(line)
    except: continue
    if d.get('type')=='llm_request':
        models.add(d.get('name'))
        a=d.get('attrs') or {}
        llm_attr_keys|=set(a.keys())
        # look for reasoning parts inside any stringified payload
        for k,v in a.items():
            if isinstance(v,str) and '"reasoning"' in v:
                reasoning_in_llm+=1
                if sample is None: sample=(k, v[:400])
                break
print('models:',models)
print('llm_request attr keys:',sorted(llm_attr_keys))
print('llm_requests containing "reasoning":',reasoning_in_llm)
print('sample:',sample)
PY

# Find embedded reasoning variants
# Search all logs for reasoning parts inside llm_request payloads and other reasoning key variants.
ROOT="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage"; echo "=== logs containing reasoning parts inside llm_request inputMessages ==="; find "$ROOT" -name main.jsonl 2>/dev/null | while read -r f; do c=$(grep -c '"type":"reasoning"' "$f" 2>/dev/null); if [ "${c:-0}" -gt 0 ]; then echo "$c  $f"; fi; done | head -20; echo "=== also check thinking/think variants ==="; find "$ROOT" -name main.jsonl 2>/dev/null | while read -r f; do grep -hoE '"(reasoning|thinking|thought)":' "$f" 2>/dev/null; done | sort | uniq -c | sort -rn | head

# Verify field type uniformity
# Determine the data types of reasoning and response fields across many logs/models.
ROOT="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage"; find "$ROOT" -name main.jsonl 2>/dev/null | head -60 | while read -r f; do python - "$f" <<'PY' 2>/dev/null
import sys,json
f=sys.argv[1]
from collections import Counter
rt=Counter(); pt=Counter(); resp_shape=Counter(); models=set()
for line in open(f,encoding='utf8',errors='ignore'):
    line=line.strip()
    if not line: continue
    try: d=json.loads(line)
    except: continue
    t=d.get('type'); a=d.get('attrs') or {}
    if t=='llm_request' and a.get('model'): models.add(a['model'])
    if t=='agent_response' or d.get('name')=='agent_response':
        if 'reasoning' in a: rt[type(a['reasoning']).__name__]+=1
        r=a.get('response')
        rt2=type(r).__name__
        # if string, is it JSON array?
        if isinstance(r,str):
            try:
                j=json.loads(r); rt2='str->'+type(j).__name__
            except: rt2='str(plain)'
        resp_shape[rt2]+=1
if rt or resp_shape:
    print('reasoning types:',dict(rt),'| response shapes:',dict(resp_shape),'| models:',sorted(models)[:3])
PY
done | sort | uniq -c | sort -rn | head -20

# Inventory response part types
# Aggregate the part types present in response arrays to ensure text extraction covers all model output shapes.
ROOT="/c/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage"; find "$ROOT" -name main.jsonl 2>/dev/null | head -40 | while read -r f; do python - "$f" <<'PY' 2>/dev/null
import sys,json
from collections import Counter
f=sys.argv[1]; pt=Counter(); msgkeys=Counter()
for line in open(f,encoding='utf8',errors='ignore'):
    line=line.strip()
    if not line: continue
    try: d=json.loads(line)
    except: continue
    if d.get('type')=='agent_response' or d.get('name')=='agent_response':
        r=(d.get('attrs') or {}).get('response')
        j=None
        if isinstance(r,str):
            try: j=json.loads(r)
            except: j=None
        if isinstance(j,list):
            for m in j:
                if isinstance(m,dict):
                    msgkeys[tuple(sorted(m.keys()))]+=1
                    for p in (m.get('parts') or []):
                        if isinstance(p,dict): pt[p.get('type')]+=1
print('part types:',dict(pt))
PY
done | tr ',' '\n' | grep -oE "'[a-zA-Z_]+': [0-9]+" | awk -F"'" '{print $2}' | sort | uniq -c | sort -rn | head

# Test multi-model capture
# Run capture against two different-model sessions (one with reasoning, one router/no-reasoning) to confirm robustness.
cd /d/cs/Devlop/A/Axiomic && node -e "
const{spawnSync}=require('child_process');
const fs=require('fs'),path=require('path');
const targets=[
 'C:/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/02dacec274c340c6583f5041ef522e69/GitHub.copilot-chat/debug-logs/557c5461-6b84-48c3-af7b-e654e4514480',
 'C:/Users/H300133/AppData/Roaming/Code - Insiders/User/workspaceStorage/02dacec274c340c6583f5041ef522e69/GitHub.copilot-chat/debug-logs/66911b60-e046-40bc-8401-2db901e191ca'
];
for(const t of targets){
 const ws='C:/Users/H300133/AppData/Local/Temp/sk-mm-'+path.basename(t);
 const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,VSCODE_TARGET_SESSION_LOG:t,SESSION_KEEPER_WORKSPACE:ws}});
 console.log('--- '+path.basename(t)+' ---');
 console.log(r.stdout.replace(/\\\\/g,'/'));
 if(r.stderr) console.error('ERR',r.stderr);
}
"

# Verify output and clean up
# Verify the models table and the assistant-text context, then clean up test dirs.
echo "=== Models table from a multi-model session ==="; sed -n '/## Models used/,/## Tool usage/p' "/c/Users/H300133/AppData/Local/Temp/sk-mm-557c5461-6b84-48c3-af7b-e654e4514480/.copilot-sessions/summary/557c5461-6b84-48c3-af7b-e654e4514480.md"; echo; echo "=== A thinking block w/ Followed by context ==="; grep -A4 "Followed by" "/c/Users/H300133/AppData/Local/Temp/sk-mm-557c5461-6b84-48c3-af7b-e654e4514480/.copilot-sessions/thinking/557c5461-6b84-48c3-af7b-e654e4514480.md" | head -8; echo; rm -rf /c/Users/H300133/AppData/Local/Temp/sk-mm-* /c/Users/H300133/AppData/Local/Temp/sk-vs-test 2>/dev/null; echo cleaned

# Final regression test
# Syntax-check and run a final regression capture on the current workspace session.
cd /d/cs/Devlop/A/Axiomic && node --check ./.github/skills/session-keeper/scripts/keep-session.mjs && echo "syntax OK" && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-final'}});console.log(r.stdout.replace(/\\\\/g,'/'));if(r.stderr)console.error('ERR',r.stderr);"; rm -rf /c/Users/H300133/AppData/Local/Temp/sk-final 2>/dev/null; echo done

# Test responses capture
# Syntax-check, run capture on the current session, and confirm the responses file contains the visible reply text.
cd /d/cs/Devlop/A/Axiomic && node --check ./.github/skills/session-keeper/scripts/keep-session.mjs && echo "syntax OK" && node -e "const{spawnSync}=require('child_process');const r=spawnSync(process.execPath,['./.github/skills/session-keeper/scripts/keep-session.mjs'],{input:'{}',encoding:'utf8',env:{...process.env,SESSION_KEEPER_WORKSPACE:'C:/Users/H300133/AppData/Local/Temp/sk-resp'}});console.log(r.stdout.replace(/\\\\/g,'/'));if(r.stderr)console.error('ERR',r.stderr);"; echo "=== responses file head ==="; ls -la "/c/Users/H300133/AppData/Local/Temp/sk-resp/.copilot-sessions/responses/" 2>/dev/null; echo "--- last response (should contain 'What I found') ---"; grep -l "What I found" "/c/Users/H300133/AppData/Local/Temp/sk-resp/.copilot-sessions/responses/"*.md 2>/dev/null && grep -A3 "What I found" "/c/Users/H300133/AppData/Local/Temp/sk-resp/.copilot-sessions/responses/"*.md 2>/dev/null | head -8

# Clean up test dir
# Remove the temp test directory.
rm -rf /c/Users/H300133/AppData/Local/Temp/sk-resp 2>/dev/null; echo cleaned

# Verify toolchain version
# Check the installed Rust toolchain version against yfinance-rs MSRV 1.91.
rustc --version && cargo --version

# cargo check the data crate
# Compile-check the new crate to validate the API usage against the real crates.
cd data && cargo check 2>&1 | tail -40
