#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session d57b342e-92a2-404c-9a23-3e8655693ea7.
# Generated by Session Keeper on 2026-06-21T02:11:06.908Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Type-check web
# Type-check the web package to confirm the edits compile.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec tsc --noEmit 2>&1 | head -30
