#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session d57b342e-92a2-404c-9a23-3e8655693ea7.
# Generated by Session Keeper on 2026-06-21T02:23:23.621Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Type-check web
# Type-check the web package to confirm the edits compile.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec tsc --noEmit 2>&1 | head -30

# Run timeframe tests
# Run the new timeframe test file to verify it passes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run src/lib/__tests__/timeframe.test.ts 2>&1 | tail -30

# Verify tests + types
# Re-run the timeframe tests and type-check the whole web package.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run src/lib/__tests__/timeframe.test.ts 2>&1 | tail -12 && pnpm exec tsc --noEmit 2>&1 | head -20

# Full web test run
# Run the full web test suite to confirm the total count and no regressions.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run 2>&1 | tail -20

# Test guard: pass case
# Run the feature-guard hook against current changes to confirm it passes (docs+tests present).
cd /d/cs/Devlop/A/Axiomic && echo '{}' | node ./.github/hooks/scripts/feature-guard.mjs; echo

# Test guard pass case
# Spawn the hook script with clean piped stdin to see its JSON output for the current (docs+tests present) change set.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync('node',['./.github/hooks/scripts/feature-guard.mjs'],{input:'{}',encoding:'utf8'});console.log('STDOUT:',r.stdout);console.error('STDERR:',r.stderr);"

# Check git status
# Inspect pending changes the guard would classify.
cd /d/cs/Devlop/A/Axiomic && git status --porcelain --untracked-files=all

# Test guard block case
# Create a temporary untracked source file, run the guard (expect a block decision), then remove the probe file.
cd /d/cs/Devlop/A/Axiomic && echo "export const x = 1;" > web/src/__guard_probe.ts && node -e "const{spawnSync}=require('child_process');const r=spawnSync('node',['./.github/hooks/scripts/feature-guard.mjs'],{input:'{}',encoding:'utf8'});console.log(r.stdout);" ; rm -f web/src/__guard_probe.ts

# Test loop guard
# Verify the stop_hook_active re-entry guard returns continue:true (no infinite loop).
cd /d/cs/Devlop/A/Axiomic && echo "export const x = 1;" > web/src/__guard_probe.ts && echo "re-entry:" && node -e "const{spawnSync}=require('child_process');const r=spawnSync('node',['./.github/hooks/scripts/feature-guard.mjs'],{input:'{\"stop_hook_active\":true}',encoding:'utf8'});console.log(r.stdout);" && rm -f web/src/__guard_probe.ts

# Final guard verification
# Final guard run against the current change set (now hooks + docs only, no app source) to confirm clean pass.
cd /d/cs/Devlop/A/Axiomic && node -e "const{spawnSync}=require('child_process');const r=spawnSync('node',['./.github/hooks/scripts/feature-guard.mjs'],{input:'{}',encoding:'utf8'});console.log(r.stdout||r.stderr);"
