#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session d57b342e-92a2-404c-9a23-3e8655693ea7.
# Generated by Session Keeper on 2026-06-21T02:18:22.120Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Type-check web
# Type-check the web package to confirm the edits compile.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec tsc --noEmit 2>&1 | head -30

# Run timeframe tests
# Run the new timeframe test file to verify it passes.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run src/lib/__tests__/timeframe.test.ts 2>&1 | tail -30

# Verify tests + types
# Re-run the timeframe tests and type-check the whole web package.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run src/lib/__tests__/timeframe.test.ts 2>&1 | tail -12 && pnpm exec tsc --noEmit 2>&1 | head -20

# Full web test run
# Run the full web test suite to confirm the total count and no regressions.
cd /d/cs/Devlop/A/Axiomic/web && pnpm exec vitest run 2>&1 | tail -20
