#!/usr/bin/env bash
#
# Terminal commands captured from Copilot session ea4986d6-1201-446c-a879-d4b129df8917.
# Generated by Session Keeper on 2026-06-30T17:03:23.662Z.
# Review before running — commands are reproduced verbatim.

set -euo pipefail
# Review git history
# Check recent history for timeframe-related files.
cd /d/cs/Devlop/A/Axiomic && git log --oneline -15 -- web/src/lib/timeframe.ts web/src/components/AnalysisWorkspace.tsx web/src/components/CandleChart.tsx

# Start dev server
# Start the Vite dev server in the background to reproduce the issue.
cd /d/cs/Devlop/A/Axiomic/web && (pnpm dev --port 5174 > /tmp/vite.log 2>&1 &) ; sleep 4; cat /tmp/vite.log

# Run tests
# Run the web test suite to verify no regressions.
cd /d/cs/Devlop/A/Axiomic/web && pnpm vitest run 2>&1 | tail -40
